### ISSUE TITLE
Application crashing with TypeError

### ISSUE THREAD

**Issue by aerben** [jackcrane/apple-music-presence#5]
First of all: Thanks a lot for the effort implementing this.
The app is crashing for me, though. If I can help with debugging (I'm actually a node.js backend developer myself) just tell me.

```
SlowDown: Reduce your request rate.
    at deserializeAws_restXmlPutObjectCommandError (/snapshot/apple-music-presence/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:8037:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /snapshot/apple-music-presence/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at async /snapshot/apple-music-presence/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at async StandardRetryStrategy.retry (/snapshot/apple-music-presence/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at async /snapshot/apple-music-presence/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20
    at async /snapshot/apple-music-presence/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at async Upload (/snapshot/apple-music-presence/s3.js:28:18)
    at async /snapshot/apple-music-presence/applescript.js:29:26 {
  '$fault': 'client',
  '$metadata': {
    httpStatusCode: 503,
    requestId: undefined,
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 3,
    totalRetryDelay: 939
  },
  Code: 'SlowDown'
}
🎺 New Song! My Friends by Red Hot Chili Peppers. As always, donations appreciated! https://www.buymeacoffee.com/jackcrane
🎺 New Song! My Friends by Red Hot Chili Peppers. As always, donations appreciated! https://www.buymeacoffee.com/jackcrane
/snapshot/apple-music-presence/applescript.js:23
          song.forEach((s) => {
               ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at /snapshot/apple-music-presence/applescript.js:23:16
    at ChildProcess.<anonymous> (/snapshot/apple-music-presence/node_modules/applescript/lib/applescript.js)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
So long and thanks for all the fish.
  -- Douglas Adams

Saving session...completed.
Deleting expired sessions...       2 completed.

[Prozess beendet]

```

**Comment by jackcrane** [comment]
Seems like a rate-limiting issue with the S3 API. Only thing we can do about that is wait until there is less activity.
